no_reply_mail: "flenglish@no-reply.com"
domain: "localhost:3000"
smtp:
  address: "smtp.gmail.com"
  port: 587
user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
    max_length: 50
comment:
  max_content: 255
remember_me:
  checked: "1"
seed:
  male: 0
  female: 1
  min_age: 16
  max_age: 60
home:
  movies: 8
  users: 10
summary:
  title_en: 20
  title_vi: 25
error_status:
  internal: 500
admin:
  summary:
    movie:
      title: 40
gender:
  male_text: "false"
  male: 0
  female: 1
gravatar:
  size:
    user: 80
    user_profile: 100
tab:
  default: "tab1"
per_page:
  comments: 10
role:
  admin: "administrator"
  member: "member"
shared:
  file:
    js:
      comment: "/app/views/shared/comment.js.erb"
default_views: 1
step:
  one: 1
view_counter: 3
text_area_size: 8
continue: "continue"
no_image: "/uploads/no-image.jpg"
picture_size: 5
controller:
  sessions: "sessions"
  registrations: "registrations"
  confirmations: "confirmations"
  passwords: "passwords"
order_by:
  desc: " desc"
  asc: " asc"
  default: "created_at desc"
